language: cpp
compiler: gcc
sudo: require
dist: xenial

before_install:
  - sudo add-apt-repository ppa:beineri/opt-qt-5.12.3-xenial -y
  - sudo apt-get update -qq

install:
  - sudo apt-get -y install qt512base qt512quickcontrols2 qt512quickcontrols qt512declarative 
  - source /opt/qt*/bin/qt*-env.sh

script:
  - qmake .
  - make -j$(nproc)
  - mkdir -p appdir/usr/bin ; strip ShareMyHost ; cp ShareMyHost appdir/usr/bin/
  - mkdir -p appdir/usr/share/applications ; cp ShareMyHost.desktop appdir/usr/share/applications/
  - mkdir -p appdir/usr/share/icons/hicolor/256x256/apps/ ; cp qml/logo.png appdir/usr/share/icons/hicolor/256x256/apps/ShareMyHost.png
  - wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
  - wget https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
  - chmod +x linuxdeploy*.AppImage
  - ./linuxdeploy-x86_64.AppImage --appdir appdir -e ShareMyHost -i appdir/usr/share/icons/hicolor/256x256/apps/ShareMyHost.png -d ShareMyHost.desktop --plugin qt --output appimage

after_success:
  - wget "https://github.com/probonopd/uploadtool/raw/master/upload.sh"
  - bash upload.sh ShareMyHost*.AppImage *zsync
  
branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/
